# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/16972/minisys/minisys.srcs/sources_1/ip/prgprom/prgprom.xci
# IP: The module: 'prgprom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/16972/minisys/minisys.srcs/sources_1/ip/prgprom/prgprom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prgprom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/16972/minisys/minisys.srcs/sources_1/ip/prgprom/prgprom.xci
# IP: The module: 'prgprom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/16972/minisys/minisys.srcs/sources_1/ip/prgprom/prgprom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prgprom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
